version: '4'

services:
  eureka:
    image: eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  gateway:
    image: gateway
    container_name: gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    networks:
      - eureka-network

  auth:
    image: auth
    container_name: auth
    depends_on:
      - eureka
    ports:
      - "8081:8081"
    networks:
      - eureka-network

  user:
    image: user
    container_name: user
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    networks:
      - eureka-network

  post:
    image: post
    container_name: post
    depends_on:
      - eureka
    ports:
      - "8083:8083"
    networks:
      - eureka-network

  comment:
    image: comment
    container_name: comment
    depends_on:
      - eureka
    ports:
      - "8084:8084"
    networks:
      - eureka-network
  
  config:
    image: config
    container_name: config
    depends_on:
      - eureka
    ports:
      - "8888:8888"
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge