server:
  # when pull at ec2, need to be changed, this address allow accessing from all ip
  host: 0.0.0.0
  port: 8761
spring:
  application:
    name: eureka
  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          service-url:
            # need to be changed to ec2 ip when pull at ec2
            defaultZone: http://eureka:8761/eureka/
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false