spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    username: park
    password: 12345678
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect