server:
  port: 8080

logging:
  level:
    org:
      springframework:
        gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: comment-service
          uri: lb:http//COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comment/**

        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**

        - id: post-service
          uri: lb:http://POST-SERVICE
          predicates:
            - Path=/api/v1/post/**