jwt:
  secret: "thisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkey"
  expiration: 3600000
server:
  port: 8081

eureka:
  client:
    service-url:
      # need to be changed when pull into EC2 Instance
      # defaultZone: http://<eureka server instance ip>:8761/eureka/
      # docker network
      defaultZone: http://host.docker.internal:8761/eureka/

spring:
  application:
    name: auth-service

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/blog
    username: root
    password: youngseo0@
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # netflix eureka client
  cloud:
    discovery:
      enabled: true
      service-id: auth-service