jwt:
  secret: "thisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkeythisisthesecretkey"
  expiration: 3600000
server:
  port: 8081

eureka:
  client:
    service-url:
      # need to be changed when pull into EC2 Instance
      # defaultZone: http://<eureka server instance ip>:8761/eureka/
      # docker network
      defaultZone: http://host.docker.internal:8761/eureka/

spring:
  application:
    name: auth-service

  # mysql
  # if you access db with public wifi, port 3306 will be blocked
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blog1.cvciag64kgix.ap-northeast-2.rds.amazonaws.com:3306/blog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: 12345678
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # netflix eureka client
  cloud:
    discovery:
      enabled: true
      service-id: auth-service