version: '3.8'
services:
  app:
    build: .
    ports: ["8080:8080"]
    depends_on: [redis]
  redis:
    image: redis:7
    container_name: blog-redis
    ports: ["6379:6379"]
  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:10.2.3
    ports: ["3000:3000"]
    depends_on: [prometheus]